PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
PermitRootLogin no
AllowUsers jeremy edsys-admin
MaxAuthTries 3
LoginGraceTime 30
AllowTcpForwarding local
AllowStreamLocalForwarding local
GatewayPorts no
AllowAgentForwarding no
X11Forwarding no
PermitTunnel no
