[core]
data_directory = /var/lib/openwebrx
temporary_directory = /var/spool/edsys-sdr/openwebrx
log_level = INFO

[web]
port = 8073
ipv6 = false
bind_address = 0.0.0.0

[aprs]
symbols_path = /usr/share/aprs-symbols/png
