[Service]
NoNewPrivileges=true
PrivateTmp=true
ProtectHome=true
ProtectClock=true
ProtectHostname=true
ProtectKernelLogs=true
ProtectKernelModules=true
ProtectKernelTunables=true
ProtectControlGroups=true
RestrictNamespaces=true
LockPersonality=true
CapabilityBoundingSet=
ReadWritePaths=/var/lib/openwebrx /var/spool/edsys-sdr/openwebrx /srv/edsys-sdr-data
